name: pipeliner

version: '0.1.0'

description: >
  TODO

dev_dependencies:
  lintorium: ^0.1.3

environment:
  sdk: '>=3.0.0 <4.0.0'

repository: https://github.com/ilexbor/pipeliner

issue_tracker: https://github.com/ilexbor/pipeliner/issues

license: 'BSD-3-Clause'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - pipe
  - pipeline
  - chain
  - middleware

