name: pipeliner

version: '0.2.1'

license: 'BSD-3-Clause'

repository: https://github.com/ilexbor/pipeliner

issue_tracker: https://github.com/ilexbor/pipeliner/issues

description: >
  Effortlessly build and manage pipelines in Dart.
  Perfect for handling sequences of tasks or transforming data step-by-step.

dev_dependencies:
  lintorium: ^1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - pipe
  - pipeline
  - transformer
  - chain
  - middleware
